using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace TradeCompany
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void AddOrder_Click(object sender, EventArgs e)
        {
            Panel1.Visible = true;
        }

        protected void AddEditOrder_Click(object sender, EventArgs e)
        {
            SqlDataSource2.Insert();
            Orders.DataBind();
            TextBoxTitle.Text = "";
            TextBoxPrice.Text = "";
            TextBoxQuant.Text = "";
            Panel1.Visible = false;
        }

        protected void CancelEditOrder_Click(object sender, EventArgs e)
        {
            TextBoxTitle.Text = "";
            TextBoxPrice.Text = "";
            TextBoxQuant.Text = "";
            Panel1.Visible = false;
        }

        protected void AddCustomer_Click(object sender, EventArgs e)
        {
            Panel2.Visible = true;
        }

        protected void AddEditCustomer_Click(object sender, EventArgs e)
        {
            SqlDataSource1.Insert();
            Customers.DataBind();
            TextBoxName.Text = "";
            TextBoxSurname.Text = "";
            TextBoxYear.Text = "";
            Panel2.Visible = false;
        }

        protected void CancelEditCustomer_Click(object sender, EventArgs e)
        {
            TextBoxName.Text = "";
            TextBoxSurname.Text = "";
            TextBoxYear.Text = "";
            Panel2.Visible = false;
        }

        protected void EditOrder_Click(object sender, EventArgs e)
        {
            if(EditOrder.Text=="Редактировать заказы") 
            {
                Orders.AutoGenerateEditButton = true;
                EditOrder.Text = "Закончить редактирование";
            }
            else 
            {
                Orders.AutoGenerateEditButton = false;
                EditOrder.Text = "Редактировать заказы";
            }
                
        }

        protected void EditCustomer_Click(object sender, EventArgs e)
        {
            if (EditCustomer.Text == "Редактировать заказчиков")
            {
                Customers.AutoGenerateEditButton = true;
                EditCustomer.Text = "Закончить редактирование";
            }
            else
            {
                Customers.AutoGenerateEditButton = false;
                EditCustomer.Text = "Редактировать заказчиков";
            }
        }

        protected void DeleteOrder_Click(object sender, EventArgs e)
        {
            if(DeleteOrder.Text=="Удалить заказ")
            {
                Orders.AutoGenerateDeleteButton = true;
                DeleteOrder.Text = "Закончить удаление";
            }
            else 
            {
                Orders.AutoGenerateDeleteButton = false;
                DeleteOrder.Text = "Удалить заказ";
            }
        }

        protected void DeleteCustomer_Click(object sender, EventArgs e)
        {
            if (DeleteCustomer.Text == "Удалить заказчиков")
            {
                Customers.AutoGenerateDeleteButton = true;
                DeleteCustomer.Text = "Закончить удаление";
            }
            else
            {
                Customers.AutoGenerateDeleteButton = false;
                DeleteCustomer.Text = "Удалить заказчиков";
            }
        }
    }
}